vich_uploader:
    db_driver: orm
    mappings:
       image_post:
           uri_prefix: /images/posts
           upload_destination: '%kernel.project_dir%/public/images/posts'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
